export const CORE_ASSETS = ['BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT', 'ADAUSDT', 'LINKUSDT'];
export const MEME_ASSETS = ['DOGEUSDT', '1000SHIBUSDT', '1000PEPEUSDT', 'WIFUSDT', '1000FLOKIUSDT', '1000BONKUSDT', 'BOMEUSDT', 'PEOPLEUSDT'];
export const RECOMMENDED_ASSETS = [
  '0GUSDT', '10000NEXUSDT', '10000SATSUSDT', '1000BTTUSDT', '1000CATUSDT', '1000NEIROCTOUSDT', '1000RATSUSDT', '1000TAGUSDT', '1000TOSHIUSDT', '1000TURBOUSDT', '1000XECUSDT', '1INCHUSDT', '2ZUSDT', '4USDT', 'AUSDT', 'AAOIUSDT', 'AAVEUSDT', 'ACEUSDT', 'ACHUSDT', 'ACTUSDT', 'ACUUSDT', 'ACXUSDT', 'AERGOUSDT', 'AEROUSDT', 'AEVOUSDT', 'AGIUSDT', 'AGLDUSDT', 'AIGENSYNUSDT', 'AIOUSDT', 'AIOZUSDT', 'AIXBTUSDT', 'AKEUSDT', 'AKTUSDT', 'ALABUSDT', 'ALCHUSDT', 'ALGOUSDT', 'ALICEUSDT', 'ALLOUSDT', 'ALPINEUSDT', 'ALTUSDT', 'AMATUSDT', 'ANIMEUSDT', 'ANKRUSDT', 'ANTHROPICUSDT', 'APEUSDT', 'APEXUSDT', 'API3USDT', 'APRUSDT', 'APTUSDT', 'ARUSDT', 'ARBUSDT', 'ARCUSDT', 'ARIAUSDT', 'ARKUSDT', 'ARKKUSDT', 'ARKMUSDT', 'ARPAUSDT', 'ARXUSDT', 'ASPUSDT', 'ASRUSDT', 'ASTERUSDT', 'ASTRUSDT', 'ASTSUSDT', 'ATUSDT', 'ATHUSDT', 'ATOMUSDT', 'AUCTIONUSDT', 'AVAUSDT', 'AVAAIUSDT', 'AVAXUSDT', 'AVNTUSDT', 'AWEUSDT', 'AXLUSDT', 'AXSUSDT', 'AZTECUSDT', 'BUSDT', 'B2USDT', 'B3USDT', 'BABYUSDT', 'BANUSDT', 'BANANAUSDT', 'BANANAS31USDT', 'BANDUSDT', 'BANKUSDT', 'BARDUSDT', 'BASEDUSDT', 'BATUSDT', 'BBUSDT', 'BBXUSDT', 'BCHUSDT', 'BEUSDT', 'BEAMUSDT', 'BEATUSDT', 'BELUSDT', 'BERAUSDT', 'BICOUSDT', 'BIGTIMEUSDT', 'BILLUSDT', 'BIOUSDT', 'BIRBUSDT', 'BLASTUSDT', 'BLENDUSDT', 'BLESSUSDT', 'BLUAIUSDT', 'BLURUSDT', 'BMNRUSDT', 'BMTUSDT', 'BNCUSDT', 'BNTUSDT', 'BOBAUSDT', 'BOBBOBUSDT', 'BOTUSDT', 'BRUSDT', 'BRETTUSDT', 'BREVUSDT', 'BROCCOLIUSDT', 'BSBUSDT', 'BSPUSDT', 'BSVUSDT', 'BTRUSDT', 'BTWUSDT', 'BXUSDT', 'BZUSDT', 'CUSDT', 'C98USDT', 'CAKEUSDT', 'CAPUSDT', 'CARVUSDT', 'CATIUSDT', 'CBRSUSDT', 'CCUSDT', 'CELOUSDT', 'CETUSUSDT', 'CFGUSDT', 'CFXUSDT', 'CGPTUSDT', 'CHILLGUYUSDT', 'CHIPUSDT', 'CHRUSDT', 'CHZUSDT', 'CKBUSDT', 'CLUSDT', 'CLOUSDT', 'COAIUSDT', 'COMPUSDT', 'COOKIEUSDT', 'COREUSDT', 'COTIUSDT', 'COWUSDT', 'CRCLUSDT', 'CRDOUSDT', 'CROUSDT', 'CROSSUSDT', 'CRVUSDT', 'CRWVUSDT', 'CTCUSDT', 'CTRUSDT', 'CVCUSDT', 'CVXUSDT', 'CYBERUSDT', 'CYSUSDT', 'DASHUSDT', 'DBRUSDT', 'DEEPUSDT', 'DEXEUSDT', 'DIAUSDT', 'DOLOUSDT', 'DOODUSDT', 'DOTUSDT', 'DRAMUSDT', 'DRIFTUSDT', 'DUSKUSDT', 'DYDXUSDT', 'DYMUSDT', 'EDENUSDT', 'EDGEUSDT', 'EDUUSDT', 'EGLDUSDT', 'EIGENUSDT', 'ELSAUSDT', 'ENAUSDT', 'ENJUSDT', 'ENSUSDT', 'ENSOUSDT', 'EPICUSDT', 'ERAUSDT', 'ESPUSDT', 'ESPORTSUSDT', 'ETCUSDT', 'ETHBTCUSDT', 'ETHFIUSDT', 'EULUSDT', 'EVAAUSDT', 'EWTUSDT', 'FUSDT', 'FARTCOINUSDT', 'FFUSDT', 'FHEUSDT', 'FIDAUSDT', 'FIGHTUSDT', 'FILUSDT', 'FLEXUSDT', 'FLNCUSDT', 'FLOCKUSDT', 'FLOWUSDT', 'FLRUSDT', 'FLUIDUSDT', 'FLUXUSDT', 'FLYUSDT', 'FOGOUSDT', 'FOLKSUSDT', 'FORMUSDT', 'FWDIUSDT', 'GALAUSDT', 'GASUSDT', 'GENIUSUSDT', 'GEVUSDT', 'GIGAUSDT', 'GIGGLEUSDT', 'GLMUSDT', 'GLWUSDT', 'GMTUSDT', 'GMXUSDT', 'GOATUSDT', 'GPSUSDT', 'GRAMUSDT', 'GRASSUSDT', 'GRIFFAINUSDT', 'GRTUSDT', 'GUNUSDT', 'GWEIUSDT', 'HUSDT', 'HAEDALUSDT', 'HANAUSDT', 'HBARUSDT', 'HEIUSDT', 'HEMIUSDT', 'HFTUSDT', 'HIGHUSDT', 'HIVEUSDT', 'HMSTRUSDT', 'HNTUSDT', 'HOLOUSDT', 'HOMEUSDT', 'HUMAUSDT', 'HYPEUSDT', 'HYPERUSDT', 'ICNTUSDT', 'ICPUSDT', 'ICXUSDT', 'IDUSDT', 'ILVUSDT', 'IMXUSDT', 'INUSDT', 'INITUSDT', 'INJUSDT', 'INTWUSDT', 'INXUSDT', 'IOUSDT', 'IOSTUSDT', 'IOTAUSDT', 'IOTXUSDT', 'IRYSUSDT', 'JASMYUSDT', 'JCTUSDT', 'JELLYJELLYUSDT', 'JSTUSDT', 'JTOUSDT', 'JUPUSDT', 'KAIAUSDT', 'KAITOUSDT', 'KASUSDT', 'KATUSDT', 'KAVAUSDT', 'KERNELUSDT', 'KGENUSDT', 'KITEUSDT', 'KMNOUSDT', 'KNCUSDT', 'KORUUSDT', 'KSMUSDT', 'KSTRUSDT', 'LAUSDT', 'LABUSDT', 'LDOUSDT', 'LIGHTUSDT', 'LINEAUSDT', 'LITEUSDT', 'LLYUSDT', 'LPTUSDT', 'LQTYUSDT', 'LRCUSDT', 'LSKUSDT', 'LTCUSDT', 'LUMIAUSDT', 'LUNA2USDT', 'LYNUSDT', 'MUSDT', 'MAGICUSDT', 'MAGMAUSDT', 'MANAUSDT', 'MANTAUSDT', 'MASKUSDT', 'MAVUSDT', 'MAVIAUSDT', 'MEUSDT', 'MEGAUSDT', 'MELANIAUSDT', 'MEMEUSDT', 'MERLUSDT', 'METUSDT', 'METISUSDT', 'MEWUSDT', 'MINAUSDT', 'MIRAUSDT', 'MITOUSDT', 'MMTUSDT', 'MNTUSDT', 'MOCAUSDT', 'MONUSDT', 'MOODENGUSDT', 'MORPHOUSDT', 'MOVEUSDT', 'MOVRUSDT', 'MTLUSDT', 'MUBARAKUSDT', 'MUUUSDT', 'MVLLUSDT', 'MYXUSDT', 'NAORISUSDT', 'NBISUSDT', 'NEARUSDT', 'NEOUSDT', 'NEWTUSDT', 'NIGHTUSDT', 'NILUSDT', 'NMRUSDT', 'NOMUSDT', 'NOTUSDT', 'NOWUSDT', 'NXPCUSDT', 'OUSDT', 'OGUSDT', 'OGNUSDT', 'OKBUSDT', 'ONDOUSDT', 'ONDSUSDT', 'ONGUSDT', 'ONTUSDT', 'OPUSDT', 'OPENUSDT', 'OPENAIUSDT', 'OPGUSDT', 'OPNUSDT', 'ORCAUSDT', 'ORCLUSDT', 'ORDERUSDT', 'ORDIUSDT', 'PARTIUSDT', 'PAXGUSDT', 'PEAQUSDT', 'PENDLEUSDT', 'PENGUUSDT', 'PHAUSDT', 'PHAROSUSDT', 'PIEVERSEUSDT', 'PIPPINUSDT', 'PIXELUSDT', 'PLAYSOUTUSDT', 'PLUMEUSDT', 'PNUTUSDT', 'POETUSDT', 'POLUSDT', 'POLYXUSDT', 'POPCATUSDT', 'PORTALUSDT', 'POWERUSDT', 'POWRUSDT', 'PRLUSDT', 'PROMPTUSDT', 'PROVEUSDT', 'PTBUSDT', 'PUFFERUSDT', 'PUMPBTCUSDT', 'PUMPFUNUSDT', 'PUNDIXUSDT', 'PURRUSDT', 'PYTHUSDT', 'QUSDT', 'QNTUSDT', 'QNTXUSDT', 'QTUMUSDT', 'RAREUSDT', 'RAVEUSDT', 'RAYDIUMUSDT', 'RDWUSDT', 'REUSDT', 'RECALLUSDT', 'REDUSDT', 'RENDERUSDT', 'RESOLVUSDT', 'REZUSDT', 'RIVERUSDT', 'RLCUSDT', 'ROAMUSDT', 'ROBOUSDT', 'RONINUSDT', 'ROSEUSDT', 'RPLUSDT', 'RSRUSDT', 'RUNEUSDT', 'RVNUSDT', 'SUSDT', 'SAFEUSDT', 'SAGAUSDT', 'SAHARAUSDT', 'SANDUSDT', 'SAPIENUSDT', 'SCRTUSDT', 'SEIUSDT', 'SENTUSDT', 'SHAZUSDT', 'SHELLUSDT', 'SIGNUSDT', 'SIRENUSDT', 'SKHYUSDT', 'SKLUSDT', 'SKRUSDT', 'SKYUSDT', 'SKYAI1USDT', 'SLPUSDT', 'SLXUSDT', 'SNTUSDT', 'SNXUSDT', 'SNXXUSDT', 'SOLAYERUSDT', 'SOMIUSDT', 'SONICUSDT', 'SOONUSDT', 'SOPHUSDT', 'SOSOUSDT', 'SPACEUSDT', 'SPCXUSDT', 'SPKUSDT', 'SPORTFUNUSDT', 'SPXUSDT', 'SQDUSDT', 'SSVUSDT', 'STABLEUSDT', 'STBLUSDT', 'STEEMUSDT', 'STGUSDT', 'STOUSDT', 'STORJUSDT', 'STRKUSDT', 'STXUSDT', 'STXXUSDT', 'SUIUSDT', 'SUNUSDT', 'SUPERUSDT', 'SUSHIUSDT', 'SXTUSDT', 'SYRUPUSDT', 'TUSDT', 'TAUSDT', 'TACUSDT', 'TAIKOUSDT', 'TAOUSDT', 'TERUSDT', 'THEUSDT', 'THETAUSDT', 'TIAUSDT', 'TLMUSDT', 'TNSRUSDT', 'TOWNSUSDT', 'TQQQUSDT', 'TRBUSDT', 'TREEUSDT', 'TRIAUSDT', 'TRUMPUSDT', 'TRUSTUSDT', 'TRUTHUSDT', 'TRXUSDT', 'TSEMUSDT', 'TSTBSCUSDT', 'TURTLEUSDT', 'TUTUSDT', 'TWTUSDT', 'UAIUSDT', 'UBUSDT', 'UMAUSDT', 'UNIUSDT', 'USUSDT', 'USARUSDT', 'USD1USDT', 'USELESSUSDT', 'USTCUSDT', 'USUALUSDT', 'VANAUSDT', 'VANRYUSDT', 'VELOUSDT', 'VELODROMEUSDT', 'VELVETUSDT', 'VETUSDT', 'VINEUSDT', 'VIRTUALUSDT', 'VRTUSDT', 'VVVUSDT', 'WUSDT', 'WALUSDT', 'WAVESUSDT', 'WAXPUSDT', 'WCTUSDT', 'WDCUSDT', 'WETUSDT', 'WHITEWHALEUSDT', 'WLDUSDT', 'WLFIUSDT', 'WOOUSDT', 'XAIUSDT', 'XANUSDT', 'XAUTUSDT', 'XCNUSDT', 'XDCUSDT', 'XLMUSDT', 'XMRUSDT', 'XNYUSDT', 'XPINUSDT', 'XPLUSDT', 'XTZUSDT', 'XVGUSDT', 'XVSUSDT', 'YBUSDT', 'YFIUSDT', 'YGGUSDT', 'ZAMAUSDT', 'ZBCNUSDT', 'ZBTUSDT', 'ZECUSDT', 'ZENUSDT', 'ZEREBROUSDT', 'ZESTUSDT', 'ZETAUSDT', 'ZILUSDT', 'ZKUSDT', 'ZKCUSDT', 'ZKPUSDT', 'ZMUSDT', 'ZORAUSDT', 'ZROUSDT', 'ZRXUSDT'
];

const allDefinedAssets = Array.from(new Set([...CORE_ASSETS, ...MEME_ASSETS, ...RECOMMENDED_ASSETS]));

const rawAssets = (process.env.SUPPORTED_ASSETS || allDefinedAssets.join(','))
  .split(',')
  .map((s) => s.trim());

allDefinedAssets.forEach(a => {
  if (!rawAssets.includes(a)) rawAssets.push(a);
});

export const SUPPORTED_ASSETS = rawAssets;

// ─── Risk Management Defaults ────────────────────────────────────
export const RISK = {
  MAX_RISK_PER_TRADE: parseFloat(process.env.MAX_RISK_PER_TRADE) || 0.01,   // 1%
  MAX_DAILY_LOSS: parseFloat(process.env.MAX_DAILY_LOSS) || 0.20,           // 20%
  MAX_PORTFOLIO_DRAWDOWN: parseFloat(process.env.MAX_PORTFOLIO_DRAWDOWN) || 0.10, // 10%
  MAX_LEVERAGE: 5,
  MAX_OPEN_POSITIONS: parseInt(process.env.MAX_OPEN_POSITIONS) || 150,
  MAX_CORE_POSITIONS: parseInt(process.env.MAX_CORE_POSITIONS) || 50,
  MAX_MEME_POSITIONS: parseInt(process.env.MAX_MEME_POSITIONS) || 50,
  MAX_RECOMMENDED_POSITIONS: parseInt(process.env.MAX_RECOMMENDED_POSITIONS) || 50,
  MIN_CONFIDENCE_THRESHOLD: parseFloat(process.env.MIN_CONFIDENCE_THRESHOLD) || 0.55,
  MIN_NET_PROFIT_TARGET: parseFloat(process.env.MIN_NET_PROFIT_TARGET) || 0.25, // $0.25 Net PnL floor
  MIN_MARGIN_FLOOR: parseFloat(process.env.MIN_MARGIN_FLOOR) || 5.0, // $5.00 minimum margin floor
  MARGIN_BALANCE_PERCENTAGE: parseFloat(process.env.MARGIN_BALANCE_PERCENTAGE) || 0.20, // 20% balance auto-scale
  MAX_DAILY_TRADES: parseInt(process.env.MAX_DAILY_TRADES) || 1000,
  EMERGENCY_VOLATILITY_THRESHOLD: 0.08, // 8% price swing triggers emergency
};

// ─── Trading Intervals ──────────────────────────────────────────
export const INTERVALS = {
  CANDLE_INTERVAL: '5m',         // 5-minute candles
  ANALYSIS_CYCLE_MS: parseInt(process.env.ANALYSIS_CYCLE_MS) || 5_000,      // run analysis every 5s (high-frequency)
  HEALTH_CHECK_MS: 15_000,       // agent health ping every 15s
  REBALANCE_INTERVAL_MS: 60_000, // rebalance every 60s
};

// ─── Agent Names ─────────────────────────────────────────────────
export const AGENT_NAMES = {
  SUPERVISOR: 'supervisor',
  MARKET: 'market',
  TECHNICAL: 'technical',
  SENTIMENT: 'sentiment',
  PREDICTION: 'prediction',
  FUSION: 'fusion',
  RISK: 'risk',
  EXECUTION: 'execution',
  PORTFOLIO: 'portfolio',
  LEARNING: 'learning',
};

// ─── Signal Actions ──────────────────────────────────────────────
export const ACTIONS = {
  BUY: 'BUY',
  SELL: 'SELL',
  HOLD: 'HOLD',
};

// ─── Trade Types ─────────────────────────────────────────────────
export const TRADE_TYPES = {
  SPOT: 'spot',
  FUTURES: 'futures',
  PAPER: 'paper',
};

export const SYSTEM_USER_ID = 'system';

export default { SUPPORTED_ASSETS, CORE_ASSETS, MEME_ASSETS, RECOMMENDED_ASSETS, RISK, INTERVALS, AGENT_NAMES, ACTIONS, TRADE_TYPES, SYSTEM_USER_ID };
